### ISSUE TITLE
Add support for Cycle2

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/views_slideshow#1]
I'd like to request that support for the [Cycle2 plugin](http://malsup.com/jquery/cycle2/) be added to this module (either instead of or in addition to the existing Cycle1 support).

Starting code for doing this can be found here: https://www.drupal.org/sandbox/BenYoung/1832338
And the issue for integrating this in Drupal's Views Slideshow module can be found here: https://www.drupal.org/node/1801332

**Comment by Graham-72** [comment]
@BWPanda thanks for this request. I will be able to take a look at this in the next week or two.

**Comment by Graham-72** [comment]
@BWPanda here it is at https://github.com/backdrop-contrib/views_slideshow_cycle2. It is just an initial port though I have got it working.
