### ISSUE TITLE
Error - deprecated ${var}, use {$var} instead

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/views_slideshow#13]
Error on PHP 8.2:

> Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /app/httpdocs/modules/contrib/views_slideshow/contrib/views_slideshow_cycle/theme/views_slideshow_cycle.theme.inc on line 114 Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /app/httpdocs/modules/contrib/views_slideshow/contrib/views_slideshow_cycle/theme/views_slideshow_cycle.theme.inc on line 117

**Comment by herbdool** [comment]
I think this will have to be merged by @backdrop-contrib/bug-squad

**Comment by laryn** [comment]
LGTM
