### ISSUE TITLE
Slideshow not working when pager is turned on

### ISSUE THREAD

**Issue by kejso** [backdrop-contrib/views_slideshow#2]
Hi,
I have one problem with Views slideshow using Cycle _(first version)_.
When I turn on pager (in Top or Bottom widget), the slideshow doesn't work. All I can see is the pager and first slide, with no action happening...
When the pager is turned off, everything works fine. Also when I turn on counter or controls instead of pager, everything works.

I get also this error when saving the view:

> Warning: implode(): Invalid arguments passed in form_error() (line 1736 z /nfsmnt/hosting2_1/7/5/756b8ff6-9407-4267-8aeb-d36a35549e5e/flosgarden.sk/sub/zahradkarstvo/core/includes/form.inc).

//using Backdrop CMS v1.5.1

Thanks in advance for any advice...

**Comment by Graham-72** [comment]
Modifying the template file views-slideshow-pager-fields.tpl.php with commit https://github.com/backdrop-contrib/views_slideshow/commit/0ee45fafadcd9761ed507eccdca927dc522ee81b enables the pager to work in Backdrop.
