### ISSUE TITLE
Pager images require styling.

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/views_slideshow#4]
It would be good to include some minimal styling for when the pager widget is used. This can be modified by the site designer.

**Comment by Graham-72** [comment]
It seems that there is some pager image styling in views_slideshow_cycle.css but the class is incorrect.

**Comment by herbdool** [comment]
The pager images are distorted when the images aren't square. Probably better just to set the height and not the width.

**Comment by Graham-72** [comment]
Thanks @herbdool I agree with you about just setting the height, rather than the height and width as inherited from the Drupal version.

**Comment by Graham-72** [comment]
Pager images would look better if a fixed height and auto width.
