### ISSUE TITLE
Errors in _views_slideshow_preprocess_views_slideshow_pager_fields()

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/views_slideshow#5]
I get these errors (on 3.1.1):

```
Notice: Undefined index: class in _views_slideshow_preprocess_views_slideshow_pager_fields() (line 239 of /var/www/vhosts/example/httpdocs/modules/contrib/views_slideshow/theme/views_slideshow.theme.inc).
Notice: Undefined index: id in _views_slideshow_preprocess_views_slideshow_pager_fields() (line 240 of /var/www/vhosts/example/httpdocs/modules/contrib/views_slideshow/theme/views_slideshow.theme.inc).
```

I think it has something to do with $attributes_array changing to $attributes in Backdrop or something like that.

**Comment by herbdool** [comment]
I'm not completely sure why but $attributes can't be used. From what I [read on d.o $attributes is a reserved variable](https://api.drupal.org/comment/50573#comment-50573), perhaps that combined with the change in Backdrop means that it now breaks where it didn't in Drupal.

This seems to work and doesn't affect anything else as as I can tell: change $attributes to $vss_attributes. In theme_views_slideshow_pager_widget_render() at line 204 of theme/views_slideshow.theme.inc:
```
  $vss_attributes['classes'] = 'widget_pager widget_pager_' . $vars['location'];
  $vss_attributes['id'] = 'widget_pager_' . $vars['location'] . '_' . $vars['vss_id'];
  return theme(views_theme_functions($vars['settings']['type'], $vars['view'], $vars['view']->display[$vars['view']->current_display]), array('vss_id' => $vars['vss_id'], 'view' => $vars['view'], 'settings' => $vars['settings'], 'location' => $vars['location'], 'vss_attributes' => $vss_attributes));
```

And in _views_slideshow_preprocess_views_slideshow_pager_fields() at line 239 in the same file:

```
  $vars['classes'][] = $vars['vss_attributes']['classes'];
  $vars['widget_id'] = $vars['vss_attributes']['id'];
```

There might be a better way to fix this.

**Comment by Graham-72** [comment]
@herbdool thanks for this. I had spent hours trying to find out why these attributes settings were disappearing! I now see there is some information at https://api.backdropcms.org/node/28554.

I think perhaps a change at line 25 of views_slideshow.module may be needed?

**Comment by herbdool** [comment]
I think you're right. I took a look at your commit. Looks better
