### ISSUE TITLE
Backdrop admin suggests this module's behaviour is wrong

### ISSUE THREAD

**Issue by auxiliaryjoel** [backdrop-contrib/views_slideshow#7]
I asked advice from Backdrop CMS admin about trouble I was having installing this module.
After reviewing it, they suggested that I raise an issue because there were problems with the instructions. 
They also said the recommendation of using the Libraries module should never be necessary. 

Backdrop admin felt this module was trying to do things "the Drupal way" instead of improving for Backdrop.

**Comment by olafgrabienski** [comment]
I'm not maintaining this module, so I'm only guessing, that as a start the module was ported without adapting all things the Backdrop way. In this case, ideally it will be improved, e.g. allowing to use it without the Libraries module.

In my opinion, it would be the best to open one issue per request. For instance open one issue called something like "Remove dependency of the Libraries module". From your report, it's not clear if there are other issues. Maybe you can ask the admin person who gave advice to you.

**Comment by Graham-72** [comment]
@auxiliaryjoel although this module still uses the separate Libraries module for linking the necessary jQuery cycle script, it will still work for you. I have used it on a number of sites and as a check have just installed it successfully on a new test site.

Yes, ideally it would be modified and a new release produced that follows the current Backdrop practice of including the jQuery script within the module.

If, as suggested by @olafgrabienski, you would kindly report separately on your difficulty with the installation instructions, I (who ported this module from Drupal) will gladly see what help I can offer.

**Comment by auxiliaryjoel** [comment]
> I'm not maintaining this module, so I'm only guessing, that as a start the module was ported without adapting all things the Backdrop way. In this case, ideally it will be improved, e.g. allowing to use it without the Libraries module.
> 
> In my opinion, it would be the best to open one issue per request. For instance open one issue called something like "Remove dependency of the Libraries module". From your report, it's not clear if there are other issues. Maybe you can ask the admin person who gave advice to you.

OK no worries I will raise the "Remove dependency of the Libraries module" issue as you've suggested. Thanks @olafgrabienski

**Comment by auxiliaryjoel** [comment]
> @auxiliaryjoel although this module still uses the separate Libraries module for linking the necessary jQuery cycle script, it will still work for you. I have used it on a number of sites and as a check have just installed it successfully on a new test site.
> 
> Yes, ideally it would be modified and a new release produced that follows the current Backdrop practice of including the jQuery script within the module.
> 
> If, as suggested by @olafgrabienski, you would kindly report separately on your difficulty with the installation instructions, I (who ported this module from Drupal) will gladly see what help I can offer.

Ok no problems @Graham-72 I'll create an issue specifying the issue I had

**Comment by Graham-72** [comment]
This is now fixed in release 1.x-3.3.0 which removes dependency on Libraries module.
