### ISSUE TITLE
Instructions relating to libraries folder are unclear

### ISSUE THREAD

**Issue by auxiliaryjoel** [backdrop-contrib/views_slideshow#9]
There is no existing libraries folder in the main directory level of Backdrop.
But that is where the libraries folder needs to be for this module to acknowledge the content inside it.
This is not described clearly in instructions, and as there is already a libraries folder inside the /modules/ directory it may be assumed that is the folder that should be used. Which it is not.

**Comment by Graham-72** [comment]
Yes, unfortunately this is no longer made clear, but is really something that should be documented with the now deprecated Libraries module.

The Libraries module relies on there being a site folder, also called Libraries, where the jQuery libraries are made available, each in a sub-folder. This folder has to be created when adding the first such library to the site. So if does not already exist it must be created when installing the jQuery cycle library required by this module. Its location is optional, there being code in the Libraries module to locate it at likely places within the site, but normally it seems best to have it in the main directory level.

The relevant current installation instruction for this Views Slideshow module is

> Install as usual, then add the required javascript libraries to their own directories jquery.cycle and (optionally) json2 within the site's libraries folder.

The concept of a site having a libraries folder may now be outdated and deprecated, but it is needed along with the Libraries module for some contributed modules that have not yet been revised.

**Comment by Graham-72** [comment]
This is now fixed in release 1.x-3.3.0 which removes dependency on Libraries module.
